@startuml
activate ExerciseFormPage
ExerciseFormPage -> UserSession: getUser()
activate UserSession

UserSession --> ExerciseFormPage: User
deactivate UserSession

ExerciseFormPage -> ExerciseController: save(Exercise, User)
activate ExerciseController

ExerciseController -> ExerciseService: save(Exercise, User)
activate ExerciseService

ExerciseService -> ExerciseMapper: save(Exercise, User)
activate ExerciseMapper

ExerciseMapper --> ExerciseService:
deactivate ExerciseMapper

ExerciseService --> ExerciseController:
deactivate ExerciseService

ExerciseController --> ExerciseFormPage: Result
deactivate ExerciseController
@enduml