@startuml
activate ExerciseFormPage
ExerciseFormPage -> ExerciseController: delete(int)
activate ExerciseController

ExerciseController -> ExerciseService: delete(int)
activate ExerciseService

ExerciseService -> ExerciseMapper: delete(int)
activate ExerciseMapper

ExerciseMapper --> ExerciseService:
deactivate ExerciseMapper

ExerciseService --> ExerciseController:
deactivate ExerciseService

ExerciseController --> ExerciseFormPage: Result
deactivate ExerciseController
@enduml