@startuml
activate MealTablePage
MealTablePage -> UserSession: getUser()
activate UserSession
UserSession --> MealTablePage: User
deactivate UserSession

MealTablePage -> MealController: getByUser(User)
activate MealController

MealController -> MealService: getByUser(User)
activate MealService

MealService -> MealMapper: getByUser(User)
activate MealMapper

MealMapper --> MealService: List
deactivate MealMapper

MealService --> MealController: List
deactivate MealService

MealController --> MealTablePage: Result
deactivate MealController
@enduml