@startuml
LoginPage -> UserController: getUser(String, String)
activate LoginPage
activate UserController

UserController -> UserService: getUser(String, String)
activate UserService

UserService -> UserMapper: getUser(String, String)
activate UserMapper

UserMapper --> UserService: User
deactivate UserMapper

UserService --> UserController: User
deactivate UserService

UserController --> LoginPage: Result
deactivate UserController

LoginPage -> UserSession: setUser(User)
activate UserSession
@enduml