@startuml
activate ExerciseFormPage
ExerciseFormPage -> UserSession: getUser()
activate UserSession

UserSession --> ExerciseFormPage: User
deactivate UserSession

ExerciseFormPage -> ExerciseController: getByUsername(String)
activate ExerciseController

ExerciseController -> ExerciseService:  getByUsername(String)
activate ExerciseService

ExerciseService -> ExerciseMapper:  getByUsername(String)
activate ExerciseMapper

ExerciseMapper --> ExerciseService: List
deactivate ExerciseMapper

ExerciseService --> ExerciseController: List
deactivate ExerciseService

ExerciseController --> ExerciseFormPage: Result
deactivate ExerciseController
@enduml