@startuml
RegisterPage -> UserController: save(User)
activate RegisterPage
activate UserController

UserController -> UserService: save(User)
activate UserService

UserService -> UserMapper: save(User)
activate UserMapper

UserMapper --> UserService
deactivate UserMapper

UserService --> UserController
deactivate UserService

UserController --> RegisterPage: Result

@enduml