@startuml
activate MealAddForm
MealAddForm -> UserSession: getInstance()
activate UserSession
UserSession --> MealAddForm: User
deactivate UserSession

MealAddForm -> MealController : save(Meal, User)
activate MealController

MealController -> MealService: save(Meal, User)
activate MealService

MealService -> MealMapper: save(Meal, User)
activate MealMapper

MealMapper --> MealService:
deactivate MealMapper

MealService --> MealController:
deactivate MealService

MealController --> MealAddForm: Result
deactivate MealController

@enduml