@startuml
UserProfilePage -> UserController: update(User)
activate UserProfilePage
activate UserController

UserController -> UserService: update(User)
activate UserService

UserService -> UserMapper: update(User)
activate UserMapper

UserMapper --> UserService:
deactivate UserMapper

UserService --> UserController:
deactivate UserService

UserController --> UserProfilePage: Result
deactivate UserController
UserProfilePage -> UserSession: setUser(User)
activate UserSession

@enduml