@startuml
activate ExerciseVisualPage
ExerciseVisualPage -> UserSession: getUser()
activate UserSession
UserSession --> ExerciseVisualPage: User
deactivate UserSession

ExerciseVisualPage -> ExerciseController: getDailyExerciseMinutesByDate(User, Date, Date)
activate ExerciseController

ExerciseController -> ExerciseService: ggetDailyExerciseMinutesByDate(User, Date, Date)
activate ExerciseService

ExerciseService -> ExerciseMapper: getDailyExerciseMinutesByDate(User, Date, Date)
activate ExerciseMapper

ExerciseMapper --> ExerciseService: Map<Date, Integer>
deactivate ExerciseMapper

ExerciseService --> ExerciseController: Map<Date, Integer>
deactivate ExerciseService

ExerciseController --> ExerciseVisualPage: Result
deactivate ExerciseController
@enduml