@startuml
activate MealVisualization
MealVisualization -> UserSession: getInstance()
activate UserSession
UserSession --> MealVisualization: User
deactivate UserSession

MealVisualization -> MealController: getByPeriod(String, Date, Date)
activate MealController

MealController -> MealService: getByPeriod(String, Date, Date)
activate MealService

MealService -> MealMapper: getByPeriod(String, Date, Date)
activate MealMapper

MealMapper --> MealService: List
deactivate MealMapper

MealService --> MealController: List
deactivate MealService

MealController --> MealVisualization: Result
deactivate MealController
@enduml