@startuml
activate MealVisualPage
MealVisualPage -> UserSession: getUser()
activate UserSession
UserSession --> MealVisualPage: User
deactivate UserSession

MealVisualPage -> MealController: getMealGroups(User, Date, Date)
activate MealController

MealController -> MealService: getMealGroups(User, Date, Date)
activate MealService

MealService -> MealMapper: getSortedDailyNutrient(User, Date, Date)
activate MealMapper

MealMapper --> MealService: Map<String, Float>
deactivate MealMapper

MealService --> MealController: Map<String, Float>
deactivate MealService

MealController --> MealVisualPage: Result
deactivate MealController
@enduml